#!/usr/bin/python

import sys

from SimpleXMLRPCServer import SimpleXMLRPCServer as Server

from mis.repository import FileRepository
from mis.server import MFSServer
from mis.datastore import Datastore
from mis.autopatcher import Autopatcher

def run(repo, port, autopatcher, datastore):
    repository = FileRepository(repo)

    server = Server(('', int(port)))
    server.register_instance(MFSServer(repository, autopatcher, datastore))
    server.serve_forever()

if __name__ == '__main__':
    try:
        repo = sys.argv[1]
        port = sys.argv[2]
        if len(sys.argv) > 3:
            autopatcher = Autopatcher(sys.argv[3])
            datastore = Datastore(sys.argv[4])
            run(repo, port, autopatcher, datastore)
        else:
            run(repo, port, None, None)
    except IndexError:
        print "usage {0} repository port [ patchfile_path datastore_path ]".format(sys.argv[0])
